[tools]
1password = "latest"
age = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
rust = "latest"
go = "latest"
starship = "latest"
usage = "latest"
bat = "latest"
opam = "latest"
ocaml = "latest"


[env]
_.file = ".config/mise/.env.json"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
