[tools]
1password = "latest"
age = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
neovim = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
